### ISSUE TITLE
2.0.2.RELEASE not compatible with 4.3.x spring-test

### ISSUE THREAD

**Issue by jdpgrailsdev** [spring-projects/spring-restdocs#531]
I recently updated a project using 2.0.1.RELEASE of the rest docs to 2.0.2.RELEASE and ran into the following issues:

```
Caused by: java.lang.NoSuchMethodError: org.springframework.mock.web.MockHttpServletRequest.getContentAsByteArray()[B
	at org.springframework.restdocs.mockmvc.MockMvcRequestConverter.convert(MockMvcRequestConverter.java:84)
	at org.springframework.restdocs.mockmvc.MockMvcRequestConverter.convert(MockMvcRequestConverter.java:57)
	at org.springframework.restdocs.generate.RestDocumentationGenerator.handle(RestDocumentationGenerator.java:199)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:55)
	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:169)
```

It appears that line 84 of `MockMvcRequestConverter` references a method that was introduced in version 5.0 of Spring:  https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/test/java/org/springframework/mock/web/test/MockHttpServletRequest.java#L413.  Not sure why this breaking change was made between version 2.0.1 and 2.0.2.  Would it be possible to revert this change so that I can continue to use the latest and greatest rest docs with the 4.3.x line of the Spring Framework?

**Comment by wilkinsona** [comment]
Unfortunately not, no. If REST Docs 2.0.x worked with Spring Framework 4.3, that was purely by happy accident. As [documented](https://docs.spring.io/spring-restdocs/docs/2.0.0.RELEASE/reference/html5/#getting-started-requirements), REST Docs 2.0 requires a minimum of Spring Framework 5.0.2. Note that I've linked to the REST Docs 2.0.0 documentation there. Framework 5.0 has always be required by REST Docs 2.0 so, as long as you're observing the documented requirements, there's no breaking change here.

**Comment by wilkinsona** [comment]
I should also have mentioned that REST Docs 1.2 is still actively maintained and is compatible with Spring Framework 4.3. That's the version you should use.

**Comment by jdpgrailsdev** [comment]
@wilkinsona Bummer.  I guess that we will just stick with 2.0.1.RELEASE until we can bump to 5.x of the spring framework.  Thanks!

**Comment by tomaszalusky** [comment]
Just note: I thought I needed 2.0.2 version for better handling of empty collections. Later I found the desired change was done as fix in https://github.com/spring-projects/spring-restdocs/issues/519 and propagated also into 1.2.5 version.
